import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, Clock, MapPin, Server, PenTool as Tool } from 'lucide-react';
import { format } from 'date-fns';
import { supabase } from '../lib/supabaseClient';

interface Incident {
  id: string;
  location: string;
  datahall: string;
  rack_number: string;
  part_type: string;
  part_identifier: string;
  u_height?: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  status: 'open' | 'in-progress' | 'resolved';
  created_at: string;
  updated_at: string;
  description: string;
  comments?: string;
  user_id: string;
  walkthrough_id: number;
}

const AuditDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [auditReport, setAuditReport] = useState<any | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchAuditReportDetails();
  }, [id]);

  const fetchAuditReportDetails = async () => {
    try {
      setLoading(true);
      setError(null);

      const { data, error } = await supabase
        .from('AuditReports')
        .select('*')
        .eq('Id', id)
        .single();

      if (error) throw error;
      setAuditReport(data);
    } catch (error: any) {
      console.error('Error fetching audit report details:', error);
      setError(error.message);
    } finally {
      setLoading(false);
    }
  };

  const getSeverityColor = (state: string) => {
    switch (state) {
      case 'Critical':
        return 'bg-red-100 text-red-800';
      case 'Warning':
        return 'bg-orange-100 text-orange-800';
      default:
        return 'bg-green-100 text-green-800';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-emerald-500"></div>
      </div>
    );
  }

  if (error || !auditReport) {
    return (
      <div className="p-6">
        <div className="max-w-3xl mx-auto bg-white rounded-lg shadow-sm p-6">
          <h1 className="text-2xl font-semibold text-red-600 mb-4">Error</h1>
          <p className="text-gray-600 mb-4">
            {error || 'Failed to load audit report details'}
          </p>
          <button
            onClick={() => navigate('/inspections')}
            className="flex items-center text-emerald-600 hover:text-emerald-700"
          >
            <ArrowLeft className="w-5 h-5 mr-2" />
            Back to Inspections
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6">
      <div className="max-w-4xl mx-auto">
        <button
          onClick={() => navigate('/inspections')}
          className="flex items-center text-gray-600 hover:text-gray-900 mb-6"
        >
          <ArrowLeft className="w-5 h-5 mr-2" />
          Back to Inspections
        </button>

        <div className="bg-white rounded-lg shadow-sm overflow-hidden">
          <div className="p-6">
            <div className="flex justify-between items-start mb-6">
              <div>
                <div className="flex items-center gap-3 mb-2">
                  <AlertTriangle className={`w-6 h-6 ${
                    auditReport.state === 'Critical' ? 'text-red-500' :
                    auditReport.state === 'Warning' ? 'text-orange-500' :
                    'text-green-500'
                  }`} />
                  <h1 className="text-2xl font-semibold">Audit Report #{auditReport.walkthrough_id}</h1>
                </div>
                <div className="flex items-center text-gray-600 gap-4">
                  <div className="flex items-center">
                    <Clock className="w-4 h-4 mr-2" />
                    {format(new Date(auditReport.Timestamp), 'PPpp')}
                  </div>
                  <div className="flex items-center">
                    <MapPin className="w-4 h-4 mr-2" />
                    {auditReport.datacenter}
                  </div>
                </div>
              </div>
              <div className="flex gap-2">
                <span className={`px-3 py-1 rounded-full text-sm font-medium ${getSeverityColor(auditReport.state)}`}>
                  {auditReport.state}
                </span>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-8 mb-8">
              <div>
                <h2 className="text-lg font-medium mb-4">Location Details</h2>
                <div className="space-y-4">
                  <div>
                    <label className="text-sm text-gray-500">Data Hall</label>
                    <p className="font-medium">{auditReport.datahall}</p>
                  </div>
                  <div>
                    <label className="text-sm text-gray-500">Generated By</label>
                    <p className="font-medium">{auditReport.user_full_name}</p>
                  </div>
                </div>
              </div>

              <div>
                <h2 className="text-lg font-medium mb-4">Report Details</h2>
                <div className="space-y-4">
                  <div>
                    <label className="text-sm text-gray-500">Issues Reported</label>
                    <div className="flex items-center gap-2">
                      <Tool className="w-5 h-5 text-gray-400" />
                      <p className="font-medium">{auditReport.issues_reported}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="space-y-6">
              <div>
                <h2 className="text-lg font-medium mb-4">Report Data</h2>
                <p className="text-gray-700 whitespace-pre-wrap">{JSON.stringify(auditReport.ReportData)}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AuditDetails;
