// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sagteapkjmhshqrbkovu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZ3RlYXBram1oc2hxcmJrb3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTk1NTQsImV4cCI6MjA2NDAzNTU1NH0.7ZrlOP4oRvTkCN6s0DvQtq23uSGwqLqAJNsFbVH8PK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);